name: Build_for_Linux_and_Windows

on: [workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.0
        env:
          CIBW_SKIP: "*musllinux*"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
