name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        run: pipx run cibuildwheel==2.5.0

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl